# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='server.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0cserver.proto\"\x1c\n\x0eGetPortRequest\x12\n\n\x02ID\x18\x01 \x01(\x03\"\x1c\n\x0cGetPortReply\x12\x0c\n\x04Port\x18\x01 \x01(\x03\x32\x35\n\x06Server\x12+\n\x07GetPort\x12\x0f.GetPortRequest\x1a\r.GetPortReply\"\x00\x62\x06proto3'
)




_GETPORTREQUEST = _descriptor.Descriptor(
  name='GetPortRequest',
  full_name='GetPortRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ID', full_name='GetPortRequest.ID', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=44,
)


_GETPORTREPLY = _descriptor.Descriptor(
  name='GetPortReply',
  full_name='GetPortReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Port', full_name='GetPortReply.Port', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=74,
)

DESCRIPTOR.message_types_by_name['GetPortRequest'] = _GETPORTREQUEST
DESCRIPTOR.message_types_by_name['GetPortReply'] = _GETPORTREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetPortRequest = _reflection.GeneratedProtocolMessageType('GetPortRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETPORTREQUEST,
  '__module__' : 'server_pb2'
  # @@protoc_insertion_point(class_scope:GetPortRequest)
  })
_sym_db.RegisterMessage(GetPortRequest)

GetPortReply = _reflection.GeneratedProtocolMessageType('GetPortReply', (_message.Message,), {
  'DESCRIPTOR' : _GETPORTREPLY,
  '__module__' : 'server_pb2'
  # @@protoc_insertion_point(class_scope:GetPortReply)
  })
_sym_db.RegisterMessage(GetPortReply)



_SERVER = _descriptor.ServiceDescriptor(
  name='Server',
  full_name='Server',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=76,
  serialized_end=129,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetPort',
    full_name='Server.GetPort',
    index=0,
    containing_service=None,
    input_type=_GETPORTREQUEST,
    output_type=_GETPORTREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SERVER)

DESCRIPTOR.services_by_name['Server'] = _SERVER

# @@protoc_insertion_point(module_scope)
